### ISSUE TITLE
`@description` behavior is counterintuitive

### ISSUE THREAD

**Issue by danielleontiev** [softwaremill/tapir#1203]
Tapir version: `0.18.0-M7`

Given the example:

```scala
case class Request(
      @description("time from") from: TimeRange,
      @description("time to") to: TimeRange,
      @description("simple field description") simpleField: String
)
```

Transforming to OpanAPI outputs this:

```yaml
components:
  schemas:
    Request:
      required:
      - from
      - to
      - simpleField
      type: object
      properties:
        from:
          $ref: '#/components/schemas/TimeRange'
        to:
          $ref: '#/components/schemas/TimeRange'
        simpleField:
          type: string
          description: simple field description
    TimeRange:
      required:
      - timestamp
      - misc
      type: object
      properties:
        timestamp:
          type: integer
        misc:
          type: string
      description: time from
```

- `simpleField` contains the description because it's primitive data type and it's schema is "inlined" into `properties`
- `from` and `to` are fields with common type of `TimeRange` and both represented as a `$ref` to one schema

The issue here that one of descriptions is missing.

The full example could be found here: https://github.com/danielleontiev/tapir-regression

So, I see a couple of ways of solving it

1) **The simplest**
Fail compilation when description is used on the field of non-primitive data type to enforce user to use the `@description` annotation on the object itself. The fact that annotating field of case class results in appearance of description in the field's case classe's schema is the most counterintuitive in this issue imo. Another option is not to fail every time but only if couple of fields with the same type have `@descriptoin` (In this case using `@description` on non-primitive fields will still place description in the object's schema in non-conflicting cases which is bad imo)

2) **Introduce 2 annotations instead of 1 - `@fieldDescription` and `@objectDescription` (or smth like this)**
And allow the usage of the first only on fields and the second - only on case classes. When `@fieldDescription` will be used on field that will be transformed into `$ref` - fail compilation and suggest to use `@objectDescription` on the case class

3) **inline schema**
If `@description` is used on non-primitive field it may be possible to inline the object description. The example above then will look like this:

```yaml
components:
  schemas:
    Request:
      required:
        - from
        - to
        - simpleField
      type: object
      properties:
        from:
          required:
            - timestamp
            - misc
          type: object
          properties:
            timestamp:
              type: integer
            misc:
              type: string
          description: time from
        to:
          required:
            - timestamp
            - misc
          type: object
          properties:
            timestamp:
              type: integer
            misc:
              type: string
          description: time to
        simpleField:
          type: string
          description: simple field description
```

Such transformation may be counterintuitive as well and it may be better to somehow control such behavior with another annotation like `@inlineSchema` or smth like this
