### ISSUE TITLE
Issue with openApi generation with IntEnum

### ISSUE THREAD

**Issue by GrebenkinV** [softwaremill/tapir#1276]
Tapir version: v0.18.0-M11
Scala version: 2.13.5

We define some int enum:
```
sealed abstract class Rank(val value: Int) extends IntEnumEntry with TapirCodecEnumeratum

object Rank extends IntEnum[Rank] with IntPlayEnum[Rank] {
  case object ZERO extends Rank(0)
  case object ONE extends Rank(1)
  case object TWO extends Rank(2)

  override def values: IndexedSeq[Rank] = findValues
}
```

Add this to endpoint, OpenAPIDocsInterpreter generates yaml doc and the result would be:
```
rank:
          type: integer
          enum:
          - '0'
          - '1'
          - '2'
```

What is the problem?
The error is that enum value should conform to its schema type, so the correct output should be:
```
rank:
          type: integer
          enum:
          - 0
          - 1
          - 2
```
