### ISSUE TITLE
Tapir OpenApi YAML drops enum validation for arrays

### ISSUE THREAD

**Issue by kamilkloch** [softwaremill/tapir#1398]
Endpoint
```scala
val getEnums = endpoint.get
    .in("enums")
    .in(query[Int]("n").validate(Validator.enumeration(List(1, 2))))
    .in(query[List[Int]]("ns").validateIterable(Validator.enumeration(List(1, 2))))
    .out(stringBody)
```
generates the following OpenAPI YAML:
```yaml
get:
      operationId: getEnums
      parameters:
      - name: n
        in: query
        required: true
        schema:
          type: integer
          enum:
          - 1
          - 2
      - name: ns
        in: query
        required: false
        schema:
          type: array
          items:
            type: integer
```

instead of
```yaml
get:
      operationId: getEnums
      parameters:
      - name: n
        in: query
        required: true
        schema:
          type: integer
          enum:
          - 1
          - 2
      - name: ns
        in: query
        required: false
        schema:
          type: array
          items:
            type: integer
            enum:
            - 1
            - 2
```
