### ISSUE TITLE
[BUG] Invalid Min/Max requirement for BigInt.

### ISSUE THREAD

**Issue by MrKustra94** [softwaremill/tapir#1415]
Tapir version: 0.18.0

Scala version: 2.13

**Problem**

We are using Tapir in the project and we found one problem with docs generation.
We need to have `BigInt` backed by string schema type. We can't back it by simple `number` API Type. The problem is with formatting of min/max constraints.
Currently, `Validator.min(0)` is rendered as:` minimum: 0.0`. For better user experience, we would like to have it represented as `minimum: 0`.

**How to reproduce?**
Firstly, define the `Schema` for the `BigInt` as follows:
```scala
implicit val positiveBigIntSchema: Schema[BigInt] = Schema(SString()).validate(Validator.min(0))
```

Then some case class:
```scala
  final case class MyClass(bigInt: BigInt)
  
  implicit val myClassSchema: Schema[MyClass] = Schema.derived
```
and attach it to some endpoint definition, which may be generated.

**Actual**
If attached to any endpoint, then generated doc would render following file:
```yaml
    MyClass:
      required:
      - bigInt
      type: object
      properties:
        bigInt:
          type: string
          minimum: 0.0 //BigInt invalid
```

**Expected**
```yaml
    MyClass:
      required:
      - bigInt
      type: object
      properties:
        bigInt:
          type: string
          minimum: 0
```

**Possible cause**
I've digged into the internals and found that the code responsible for such translation is placed in:
`sttp.tapir.docs.apispec.schema.TSchemaToASchema`.
The problem is with following flag set-up:

```scala
val wholeNumbers = schema.schemaType match {
    case TSchemaType.SInteger() => true
    case _                      => false
}
```
