### ISSUE TITLE
[BUG] enumeration schema generation incorrect

### ISSUE THREAD

**Issue by andyczerwonka** [softwaremill/tapir#1444]
Tapir version: 0.19.0-M1
Scala version: 2.13.5

The [enumeratum integration](0.19.0-M1) does not use the `entryName` for schema generation.

There is a fairly common pattern in enumeration to use [mixins to override the name.](https://github.com/softwaremill/tapir/issues/829#issuecomment-902692013). You can also override the `entryName` [manually](https://github.com/lloydmeta/enumeratum#manual-override-of-name). When using this pattern, the documentation generated uses the enum class name, which is incorrect. 

See https://github.com/softwaremill/tapir/issues/829#issuecomment-902692013 for more context.

**Comment by MichalPawlicki** [comment]
Given this enum:
```scala
sealed trait FruitType extends EnumEntry with Hyphencase

object FruitType extends Enum[FruitType] {
  case object Apple extends FruitType
  case object GreenPear extends FruitType
  case object VeryBlueBerry extends FruitType with Uppercase
  override def values: IndexedSeq[FruitType] = findValues
}
```
and this import in scope:
```
import sttp.tapir.codec.enumeratum._
```
I'm getting the following schema definition:
```yaml
components:
  schemas:
    FruitType:
      type: string
      enum:
        - apple
        - green-pear
        - VERY-BLUE-BERRY
```
Is this the expected behavior?
