### ISSUE TITLE
Feature request: open product with non-open fields

### ISSUE THREAD

**Issue by johnhungerford** [softwaremill/tapir#1699]
OpenAPI and JSON schema both support schemas of the following form:

```
    FailureResponse:
      required:
      - status
      - message
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
      additionalProperties:
        type: string
```

The `FailureResponse` object described above has two "determinate" fields, corresponding to an `SProduct`, but also supports `additionalProperties` of some given type, like `SOpenProduct`. It would be useful to support this kind of object in tapir, since it is sometimes necessary to have one or more required fields within an otherwise open dictionary.
