### ISSUE TITLE
AsyncApi - wrong docs for securitySchemes

### ISSUE THREAD

**Issue by kamilkloch** [softwaremill/tapir#1701]
The following doc is generated for cookie-based authentication:
```yaml
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      name: webapiuser-session
      in: cookie
```
This results in parsing error, as `apiKey` does not accept `in: cookie` (Valid values are "user" and "password" for apiKey and "query", "header" or "cookie" for httpApiKey: https://www.asyncapi.com/docs/specifications/v2.2.0#securitySchemeObject)

Changing `type` to `httpApiKey` fixes the issue:

```yaml
  securitySchemes:
    apiKeyAuth:
      type: httpApiKey
      name: webapiuser-session
      in: cookie
```
