### ISSUE TITLE
[BUG] Non optional fields with primitive types are not marked as required in output yaml

### ISSUE THREAD

**Issue by Pask423** [softwaremill/tapir#1719]
Tapir version: 0.20.0-M3

Such code :
```
val pagingQuery = query[Int]("limit")
      .description("GET `limit` field description")
      .and(query[Option[Int]]("offset").description("GET `offset` field description"))

    val personEndpoint = endpoint.get
      .in("persons" / pagingQuery)
      .out(webSocketBody[String, CodecFormat.TextPlain, Json, CodecFormat.Json](AkkaStreams).description("Endpoint description"))

    val actualYaml = AsyncAPIInterpreter().toAsyncAPI(personEndpoint, "Query descriptions", "1.0").toYaml
```
results in field `limit` from query marked as non-required while it should be marked as required.

Current output:
```
query:
          type: object
          properties:
            limit:
              type: integer
```

Desired output:
```
query:
          type: object
          properties:
            limit:
              required:
                - limit
              type: integer
```
