### ISSUE TITLE
[BUG] enumeration schema support

### ISSUE THREAD

**Issue by borissmidt** [softwaremill/tapir#1756]
Tapir version: 0.19

**Describe the bug**
Body with request `@jsonbody` fails to derive the EndpointInput when class has an Enumeration or Enum type member. 

*** Fix ***
we have to add to the Schema implicits: 
```
  implicit def schemEnumeration[T <: Enumeration#Value]: Schema[T] = Schema(SString())
```

**Comment by borissmidt** [comment]
Oh super , thank you for fixing this issue! @kubinio123

**Comment by chessman** [comment]
@kubinio123 @adamw As I understood, the PR added support for auto schema derivation, but what about semi-auto? It doesn't compile:
```
  object Enums extends Enumeration {
    val one, two, three = Value
  }

  implicit val schema: Schema[Enums.Value] = Schema.derived
```

```
[E]      magnolia: could not infer Schema.Typeclass for type com.example.TapirTest.Enums.Value
[E]      L35:   implicit val schema: Schema[Enums.Value] = Schema.derived
```

**Comment by borissmidt** [comment]
@chessman i think you need to use Enums#Value.

**Comment by chessman** [comment]
@borissmidt like this?
```
  implicit val schema: Schema[Enums#Value] = Schema.derived
```
got the following error:
```
[E]      not found: type Enums
[E]      L40:   implicit val schema: Schema[Enums#Value] = Schema.derived
[E]                                         ^^^^^

```
I think, type projection cannot be inside an object.

**Comment by borissmidt** [comment]
I think you need to import your enum where you use the implicit def so `import mypackage.Enums`

**Comment by chessman** [comment]
@borissmidt it is defined a few lines above. You would get the same error here: `object A { }; val a: A`. An object is not a type.

**Comment by kubinio123** [comment]
Derivation for enumeration got it's own macro, try using `Schema. derivedEnumerationValue ` instead

**Comment by adamw** [comment]
@kubinio123 maybe this should go into the schema derivation docs :)

**Comment by chessman** [comment]
@kubinio123 something is still not good. it doesn't produce a list of possible values in the openapi schema. compare `derivedEnumerationValue` with a more verbose variant:
```
  implicit val schema: Schema[Enums.Value] = Schema.derivedEnumerationValue
```
```
components:
  schemas:
    Input:
      required:
      - e
      type: object
      properties:
        e:
          type: string
```
```
  implicit val schema: Schema[Enums.Value] =
    Schema.string.validate(Validator.enumeration(Enums.values.toList, Option.apply))
```
```
components:
  schemas:
    Input:
      required:
      - e
      type: object
      properties:
        e:
          type: string
          enum:
          - one
          - two
          - three
```
