### ISSUE TITLE
[BUG] Annotations have no effect on Option types

### ISSUE THREAD

**Issue by chessman** [softwaremill/tapir#1920]
Tapir version: 0.20.1

Scala version: 2.12.15

**Describe the bug**

Annotations have no effect on Option types.

**How to reproduce?**

```
  case class A(s: String)
  case class Input(
    @encodedExample(A("a").asJson)
    @default(A("a"), Some("a"))
    a: Option[A]
  )
```

It generates schema without `default` and `example` fields:
```
components:
  schemas:
    A:
      required:
      - s
      type: object
      properties:
        s:
          type: string
```

**Additional information**

It doesn't work for case classes but works for `Option[String]`.
