### ISSUE TITLE
[BUG] BigDecimal fields appear with type "string" in generated OpenApi specification

### ISSUE THREAD

**Issue by slavaschmidt** [softwaremill/tapir#2107]
Tapir version: 1.0.0-M6

Scala version: 2.12.15

**Describe the bug**

Model fields of type BigDecimal have type 'string' in generated OpenApi specification

**How to reproduce?**

For example 

`final case class Verification(status: VerificationStatus, score: BigDecimal)`

appears as

```yaml
Verification:
  required:
  - status
  - score
  type: object
  properties:
    status:
      type: string         
    score:
      type: string
```

Thank you!
