### ISSUE TITLE
Enumeratum support

### ISSUE THREAD

**Issue by mpapillon** [softwaremill/tapir#224]
I would like to use `ValueEnum`s of [Enumeratum](https://github.com/lloydmeta/enumeratum) with tapir. However, the generated swagger schema is wrong.

Scala code for enum and payload case class :
```scala
sealed abstract class StreamState(val value: String) extends StringEnumEntry

object StreamState extends StringEnum[StreamState] with StringCirceEnum[StreamState] {

  override def values: immutable.IndexedSeq[StreamState] = findValues

  case object Started extends StreamState("started")
  case object Planned extends StreamState("planned")
}

final case class ProcessState(processState: StreamState)
```

Generated schema :
```yaml
components:
  schemas:
    ProcessState:
      required:
      - processState
      type: object
      properties:
        processState:
          $ref: '#/components/schemas/StreamState'
    StreamState:
      oneOf:
      - $ref: '#/components/schemas/Started'
      - $ref: '#/components/schemas/Planned'
    Started:
      type: object
    Planned:
      type: object
```

This is wrong, because the JSON generated by circe looks like : 
```json
{
  "processState": "started"
}
```

I expected a YAML like this :
```yaml
components:
  schemas:
    ProcessState:
      required:
        - processState
      type: object
      properties:
        processState:
          type: string
          enum: [started, planned]
```

**Comment by mpapillon** [comment]
Thanks for help, but the validator does not seem to be discovered by the implicit resolution.

```yaml
components:
  schemas:
    ProcessState:
      required:
      - processState
      type: object
      properties:
        processState:
          type: string
```
