### ISSUE TITLE
[QUESTION] What is the expected OpenAPI description of a custom Validator?

### ISSUE THREAD

**Issue by willemvermeer** [softwaremill/tapir#2329]
Tapir version: 1.0.2

Scala version: 2.13.8

**Describe the question**

The following code snippet:
```
  val testPath: EndpointInput[Int] =
    path[Int]("someval")
      .validate(
        Validator.all(
          Validator.max(10),
          Validator.custom[Int]((i: Int) => ValidationResult.validWhen(i == 2), Some("When printed?")
          )
        )
      )

  val example =
    unsecureEndpoint
      .get
      .in("test")
      .in(testPath)

```
produces the following openapi spec (through `OpenAPIDocsInterpreter.toOpenAPI()`):
```
...
      parameters:
      - name: someval
        in: path
        required: true
        schema:
          type: integer
          format: int32
          maximum: 10
...
```
with no reference being made to the custom validator.

The validation does in fact take place:
```
$ curl http://localhost:8084/test/3
Invalid value for: path parameter someval (expected value to pass validation, but was: 3)%
```

Is there a way to make a custom Validator appear in the OpenAPI spec?
