### ISSUE TITLE
Feature request: oneOf for primitive types

### ISSUE THREAD

**Issue by payurgin** [softwaremill/tapir#448]
`OAS 3+` allows mix any types inside `oneOf`
https://swagger.io/docs/specification/data-models/data-types/

Simple example from documentation:
```
oneOf:
  - type: string
  - type: integer
```

I not found any way to achieve similar behavior with tapir.
I think it will be good to support schemas and validators for `oneOf` with primitive types

**Comment by adamw** [comment]
This is supported e.g. using `Either` codecs. For example, given: `.in(query[Either[String, Int]]("x"))`, in the docs you get:

```
      parameters:
      - name: x
        in: query
        required: true
        schema:
          oneOf:
          - type: integer
          - type: string
```
