### ISSUE TITLE
Inline some schemas in generated OpenAPI

### ISSUE THREAD

**Issue by harpocrates** [softwaremill/tapir#485]
OpenAPI lets users specify schemas either as a reference to another schema, or inline. If you want to use a reference, you must name it (and consequently it shows up in Swagger UI). It would be nice if `tapir` exposed the choice about whether or not a schema should be inlined.

For instance, I would almost always prefer fields of type `Map` to have their schemas inlined instead of synthesizing a new `Map_<Something>` schema. Example:

```scala
case class Zoo(
  name: String,
  animalCount: Map[String, Int]
)
```

currently generates an OpenAPI schema YAML that looks like

```
components:
  schemas:
    Zoo:
      required:
      - name
      - animal_count
      type: object
      properties:
        name:
          type: string
        animal_count:
          $ref: '#/components/schemas/Map_Int'
    Map_Int:
      type: object
      additionalProperties:
        type: integer
```

I would like a way to avoid the unsightly `Map_Int` completely 

```
components:
  schemas:
    Zoo:
      required:
      - name
      - animal_count
      type: object
      properties:
        name:
          type: string
        animal_count:
          type: object
          additionalProperties:
            type: integer
```

Note that as a workaround I can just re-arrange the `sttp.tapir.openapi.Components` object to inline some references into their schemas.
