### ISSUE TITLE
[BUG] Duplicated enum property in openapi when wrapping enumeratum enum with array

### ISSUE THREAD

**Issue by ghostbuster91** [softwaremill/tapir#657]
Tapir version: 0.16.1

**Describe the bug**

What is the problem?

Openapi description is incorrect:
```
    MyObject:
      type: object
      properties:
        someDate:
          type: string
          format: date-time
        someString:
          type: string
        myAttribute:
          type: array
          items:
            type: string
            enum:
            - ENUM1
            - ENUM2
            - ENUM3
            - ENUM4
          enum:
          - ENUM1
          - ENUM2
          - ENUM3
          - ENUM4
```
while it shoulb be:
```
    MyObject:
      type: object
      properties:
        someDate:
          type: string
          format: date-time
        someString:
          type: string
        myAttribute:
          type: array
          items:
            type: string
            enum:
            - ENUM1
            - ENUM2
            - ENUM3
            - ENUM4
```

**How to reproduce?**
use tapir-enumeraturm module and generate openapi description for:
```
case class MyObject(
    someDate: Option[OffsetDateTime],
    someString: Option[String],
    myAttribute: List[ProblemEnum]
)

sealed abstract class ProblemEnum extends EnumEntry

case object ProblemEnum extends Enum[ProblemEnum] {

  case object ENUM1 extends ProblemEnum
  case object ENUM2 extends ProblemEnum
  case object ENUM3 extends ProblemEnum
  case object ENUM4 extends ProblemEnum

  override def values: scala.collection.immutable.IndexedSeq[ProblemEnum] = findValues

}
```

cc @ionutioio
