### ISSUE TITLE
Handling of value classes

### ISSUE THREAD

**Issue by sebastianvoss** [softwaremill/tapir#71]
I'm using value classes to have a type-safe representation of e.g. IDs.

For example, I have this case class:

`case class UserId(value: String) extends AnyVal`

With the help of `io.circe.generic.extras.deriveUnwrappedEncoder` this is represented in JSON as `"id": "1"` instead of `"id": {"value": "1"}`.

How can I make tapir aware of this situation. It currently outputs this OpenAPI doc:

```
id:
  required:
  - value
  type: object
  properties:
    value:
      type: string
```
instead of:
```
id:
  type: string
```
