### ISSUE TITLE
[Feature Request] Override the security component name

### ISSUE THREAD

**Issue by soujiro32167** [softwaremill/tapir#849]
### Use Case

I want my API to be part of a Swagger UI API aggregator (some apis from Tapir, some not):
```js
const ui = SwaggerUIBundle({  
    urls: [   
        { url: "http://petstore.swagger.io/v2/swagger.json", name: "Pets" },  
        { url: "https://idratherbewriting.com/learnapidoc/docs/rest_api_specifications/openapi_openweathermap.yml", name: "Weather" }  
    ], 
 ...
}
```

When I click the green authorize button 
![image](https://user-images.githubusercontent.com/6598104/98587541-48ff5b00-2298-11eb-8f66-c074b8c0c9a9.png),
I would like for all aggregated api to use that authorization

### Problem

For this to happen, all `security` component references have to align. In this example, they all align to `bearerAuth`
```yaml
security:
 - bearerAuth: []
components:
  securitySchemes:
    - bearerAuth:
         type: http
         scheme: bearer
pahts:
  /example:
    get:
      security:
        - bearerAuth: []
```

However, given an endpoint `endpoint.get.in(bearer.auth[String])`, we would get `httpAuth` by default

### Proposal

`endpoint.get.in(bearer.auth[String].name("MyBearerAuth"))` would override the default security scheme name
